//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 5.0.29.893
//     Runtime Version: 4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}

namespace DataSnapdotnetClient;

interface

type
    MainForm = public partial class
    protected 
        var Head1: System.Web.UI.HtmlControls.HtmlHead;
        var form1: System.Web.UI.HtmlControls.HtmlForm;
        var Label1: System.Web.UI.WebControls.Label;
        var tbUsername: System.Web.UI.WebControls.TextBox;
        var Label2: System.Web.UI.WebControls.Label;
        var tbPassword: System.Web.UI.WebControls.TextBox;
        var btLogin: System.Web.UI.WebControls.Button;
        var cvUser: System.Web.UI.WebControls.Label;
        var ButtonParams: System.Web.UI.WebControls.Button;
        var GridPanel: System.Web.UI.WebControls.Literal;
        var Button1: System.Web.UI.WebControls.Button;
        var GridView1: System.Web.UI.WebControls.GridView;
        var ButtonSend: System.Web.UI.WebControls.Button;
    end;
    
implementation

end.
